# Generated by Django 2.1.4 on 2018-12-05 11:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ventaproductos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('modificacion', models.DateTimeField(auto_now=True)),
                ('cantidad', models.FloatField(blank=True, default=0, null=True)),
                ('precioventa', models.FloatField(blank=True, default=0, null=True)),
                ('activo', models.BooleanField(blank=True, default=True)),
                ('estado', models.BooleanField(blank=True, default=True)),
            ],
            options={
                'db_table': 'aplicacion_venta_productos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Anulacionventa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('estado', models.BooleanField(blank=True, default=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Aperturacaja',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('monto', models.FloatField()),
                ('activo', models.BooleanField(blank=True, default=True)),
                ('estado', models.BooleanField(blank=True, default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Caja',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=45)),
                ('estado', models.BooleanField(blank=True, default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Cierrecaja',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('monto', models.FloatField()),
                ('estado', models.BooleanField(blank=True, default=True)),
                ('aperturacaja', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aplicacion.Aperturacaja')),
            ],
        ),
        migrations.CreateModel(
            name='Lote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('modificado', models.DateTimeField(auto_now=True)),
                ('proveedor', models.CharField(max_length=45)),
                ('estado', models.BooleanField(blank=True, default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=45)),
                ('codigo', models.CharField(blank=True, max_length=45, null=True)),
                ('unidad', models.CharField(blank=True, max_length=10, null=True)),
                ('cantidad', models.FloatField(blank=True, default=0, null=True)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='')),
                ('url', models.CharField(blank=True, max_length=100, null=True)),
                ('precioxmenor', models.FloatField(blank=True)),
                ('precioxmayor', models.FloatField(blank=True, null=True)),
                ('estado', models.BooleanField(blank=True, default=True)),
            ],
            options={
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('monto', models.FloatField(blank=True, null=True)),
                ('nrecibo', models.CharField(blank=True, max_length=45, null=True)),
                ('estado', models.BooleanField(blank=True, default=True)),
                ('anulacionventa', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='aplicacion.Anulacionventa')),
                ('aperturacaja', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='aplicacion.Aperturacaja')),
                ('productos', models.ManyToManyField(to='aplicacion.Producto')),
            ],
            options={
                'ordering': ['-fecha'],
            },
        ),
        migrations.AddField(
            model_name='lote',
            name='productos',
            field=models.ManyToManyField(to='aplicacion.Producto'),
        ),
        migrations.AddField(
            model_name='aperturacaja',
            name='caja',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aplicacion.Caja'),
        ),
    ]
