# Generated by Django 2.1.4 on 2018-12-05 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='ventaproductos',
            table='app_venta_productos',
        ),
    ]
