# Generated by Django 2.1.4 on 2018-12-05 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0002_auto_20181205_1151'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoteProductos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('modificacion', models.DateTimeField(auto_now=True)),
                ('cantidad', models.FloatField(blank=True, default=0, null=True)),
                ('activo', models.BooleanField(blank=True, default=True)),
                ('estado', models.BooleanField(blank=True, default=True)),
            ],
            options={
                'db_table': 'aplicacion_lote_productos',
                'managed': False,
            },
        ),
        migrations.AlterModelTable(
            name='ventaproductos',
            table='aplicacion_venta_productos',
        ),
    ]
