# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-04-03 21:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='producto',
            options={'ordering': ['nombre']},
        ),
    ]
