# Generated by Django 2.1 on 2018-09-17 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_remove_anulacionventa_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lote',
            name='proveedor',
            field=models.CharField(blank=True, max_length=45, null=True),
        ),
    ]
